GET http://localhost:8081/doc/list?page=1&size=3
Accept: application/json

###

POST http://localhost:8081/doc/save
Content-Type: application/json

{
  "name": "aaa",
  "sort": 1,
  "parent": 100
}

###删除接口

DELETE http://localhost:8081/doc/delete/1
Content-Type: application/json


###
GET http://localhost:8081/doc/list?name=Spring
Accept: application/json

###