GET http://localhost:8081/user/list?page=1&size=3
Accept: application/json

###

POST http://localhost:8081/user/save
Content-Type: application/json

{
  "id":1
}
###删除接口

POST http://localhost:8081/user/delete
Content-Type: application/json

{
  "id": 1
}

###
POST http://localhost:8081/user/login
Content-Type: application/json

{
  "loginName": "test",
  "password": "test123"
}

###
GET http://localhost:8081/user/logout/20359600725430272
Accept: application/json

###